### ISSUE TITLE
postpone Model.PopulateRoutes()

### ISSUE THREAD

**Issue by MignonBelongie** [nicky-nym/city3d#37]
Model.PopulateRoutes() is taking over 3 seconds on my machine after selecting Latticeburg. It would be better to postpone the call, and break it up into smaller chunks.

**Comment by nicky-nym** [comment]
It would be interesting to know what pieces of populateRoutes() are taking the most time. For instance, if we only generated 'lowRes' vehicles, I'm assuming that would speed things up by more than 3x, but maybe by a lot more? And it would be interesting to know if there are other things we could do to improve performance, like whether using instances might help, or only populating routes that are in view of the camera, or using super-low-res vehicles that are just one triangle per vehicle?

**Comment by MignonBelongie** [comment]
There are lots of things that can speed up rendering of Movers, but what I'm focusing on right now is trying to improve responsiveness by breaking up functionality into smaller chunks that can be run asynchronously. I do also plan to look at InstancedMesh soon.
